# /.github/workflows/test-0cherry-github-action.yml
name: Vulcan Demo

on:
  workflow_dispatch:
  # push

jobs:
  vulcan:
    runs-on: self-hosted

    steps:
      - name: Test vulcan action
        uses: Suresoft-GLaDOS/vulcan-action@report-patch-validation
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: vulcan_target
          validator: AI
