# /.github/workflows/test-0cherry-github-action.yml
name: Vulcan Demo

on:
  workflow_dispatch:
  # push

jobs:
  vulcan:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout vulcan target
        uses: actions/checkout@v2
      - name: Run vulcan action
        uses: Suresoft-GLaDOS/vulcan-action@main
