# /.github/workflows/test-0cherry-github-action.yml
name: Vulcan Demo

on:
  workflow_dispatch:
  # push

jobs:
  vulcan:
    runs-on: ubuntu-20.04

    steps:
      - name: Test vulcan action
        uses: Suresoft-GLaDOS/vulcan-action@feature-runner-setting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: vulcan_target
